### Get books
GET http://localhost:4000/books

### Create a book
POST http://localhost:4000/books
Content-Type: application/json

{
    "title": "This is my awesome book",
    "author": "Loren Vandervort",
    "rating": 1.9,
    "year_published": 1848
}

### Replace a book
PUT http://localhost:4000/books/b8dd
Content-Type: application/json

{
    "id": "b8dd",
    "title": "This is my awesome book",
    "author": "Loren Vandervort",
    "rating": 1.9,
    "year_published": 1848
}

### Update a book
PATCH http://localhost:4000/books/e704
Content-Type: application/json

{
    "rating": 2.5,
    "year_published": 2000
}

### Delete a book
DELETE http://localhost:4000/books/e704